#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use App\Console\Commands\TestCmd;
use App\Console\Commands\MakeController;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new TestCmd("hello console"));
$application->add(new MakeController("TestController"));
$application->run();